name: pcstore
description: "store app"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.2.1
  http: ^1.0.0

  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  provider: ^6.0.5
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^3.0.7
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  shared_preferences: ^2.3.5
  flutter_secure_storage: ^9.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.0.0
  
  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  assets:
      - assets/images/
      - .env

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # see https://flutter.dev/to/font-from-package